/** biome-ignore-all lint/complexity/noArguments: ignore */
import { Montserrat, Poppins } from 'next/font/google';
import './globals.css';

// Components
import Header from '@/components/Header';
import Footer from '@/components/Footer';

// Fonte para os títulos
const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['500', '700', '900'], 
  variable: '--font-montserrat', 
});

// Fonte para o corpo do texto
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600'], 
  variable: '--font-poppins',
});

export const metadata = {
  title: 'Seu Impulso Digital', 
  description: 'Generated by create next app', 
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <head>
        {/* Google tag (gtag.js) */}
        <Script async src="https://www.googletagmanager.com/gtag/js?id=AW-17583189019"></Script>
        <Script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments)}
          gtag('js', new Date());

          gtag('config', 'AW-17583189019');
        </Script>
      </head>
      <body className={`${montserrat.variable} ${poppins.variable} antialiased`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}