import { Montserrat, Poppins } from 'next/font/google';
import './globals.css';

// Components
import Header from '@/components/Header';

// Fonte para os títulos
const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['500', '700', '900'], 
  variable: '--font-montserrat', 
});

// Fonte para o corpo do texto
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600'], 
  variable: '--font-poppins',
});

export const metadata = {
  title: 'Seu Impulso Digital', 
  description: 'Generated by create next app', 
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={`${montserrat.variable} ${poppins.variable} antialiased`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}